name: Git Auto Commit
on: 
jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: stefanzweifel/git-auto-commit-action@v5
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 