import pyautogui as gui
import time
import random
# time.sleep(10)
screenWidth, screenHeight = gui.size()
currentMouseX, currentMouseY = gui.position()
# print(currentMouseX, currentMouseY)
# gui.moveTo(1278, 52)
# gui.leftClick()
# gui.leftClick()
# gui.moveTo(995, 182)
# gui.leftClick()
# time.sleep(7.5)
# gui.moveTo(1178, 701)
# gui.leftClick()
# gui.hotkey()
    # gui.moveTo(1000, 500, 2)
    # gui.leftClick()
    # time.sleep(1)
    # gui.hotkey('command', 't')
    # gui.moveTo(1211, 105, 2)
    # gui.leftClick()
    # gui.write('blockyplayer.github.io/index.html', 1)
    # gui.hotkey('enter')
# # # # t = random.randint(1, 3)
# # # # gui.moveTo(920, 1046, 2)
# # # # gui.leftClick()

# # # # time.sleep(t+2)
# # # # gui.moveTo(830, 592, t)
# # # # gui.leftClick()
# # # # gui.scroll(-20)
# # # # gui.hotkey('a')
# # # # time.sleep(1)
# # # # gui.hotkey('delete')
# # # # gui.moveTo(267, 93, t)
# # # # gui.leftClick()
# # # # gui.moveTo(295, 110, t)
# # # # gui.leftClick()
# # # # gui.moveTo(467, 116, t)
# # # # gui.moveTo(467, 175, t)
# # # # gui.leftClick()
# # # # gui.dragTo(800, None, button='middle', duration=t)
# # # # time.sleep(t)
# # # # gui.press('s')
# # # # gui.press('y')
# # # # time.sleep(t)
# # # # gui.moveTo(1000, 500, duration=t)
# # # # gui.leftClick()
gui.screenshot('win10_logo.png', region=(755, 455, 855, 555))
location = gui.locateOnScreen('win10_logo.png')
gui.click(location)

# # # # gui.hotkey('shift', 'd')
# # # # time.sleep(t)
# # # # gui.moveTo(1000, 500)